### ISSUE TITLE
Optics not Compatible with Shaders

### ISSUE THREAD

**Issue by Type-32** [ClumsyAlien/TimelessandClassics_Reforged#100]
**Platform:** Windows 10
**Specs:** RTX 3050 8GB VRAM, 32GB RAM, i5-Gen6
**Mod Version:** tac-a-0.3.6.1_1388-1.16.5**
**Mods Used:**
![image](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/87076491/d96ed908-4b8f-40c8-bb94-a72a0dcd219d)
![image](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/87076491/6a51cf9f-fa15-42d1-b519-2b7cb5aefddd)

**Bug Description:**
Using Certain Shaders (Screenshot Shader: ComplementaryShaders V4.5; Bug also occurs using other shaders such as ComplementaryReimagined, Sildur's Shaders, SEUS, Continuum, MakeFast-Ultra, etc.) breaks the Scope rendering for the following:

- ACOG 4x
- Vortex LPVO
- ELCAN Specter DR 1x-4x
- QMK152
- Standard 8x Scope

All Scopes Listed above appear in this way.
![image](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/87076491/58a2d45d-7542-4433-b8f4-46c48e8d6bf2)

**Comment by ClumsyAlien** [comment]
This is very well known, there is an option called DR and you turn if off in order to work with shaders. This is required for using any zoom scope.

**Comment by Type-32** [comment]
New Edit: I found the option after removing Rubidium + Oculus and using Optifine. Somehow the TAC GUI Button doesn't show up, presumably caused by Rubidium/Sodium's UI Change.

**Comment by ClumsyAlien** [comment]
The settings can also just be found within the config file if you wish to still use Rubidium + Oculus, this is changed for future versions, since we don't support the idea of using Optifine past 1.16.5.
