### ISSUE TITLE
Scope Zooming Operations Are Not Separate

### ISSUE THREAD

**Issue by Type-32** [ClumsyAlien/TimelessandClassics_Reforged#101]
Zooming one scope on one gun zooms all the other scopes on all the other guns.

**Comment by ClumsyAlien** [comment]
I don't understand what you mean by this? You are only able to hold one gun, and all scope rendering is done per client, not server wide among all players.

**Comment by Type-32** [comment]
Let me elaborate more on the issue:
Right now I have two guns and each has a zoomable scope. For instance, gun one has a standard x8 scope and gun two has a ELCAN scope. The Standard x8 Scope is now on Max Zoom Level, and the ELCAN scope is now on 1x Zoom Level.
When I hold gun one and press the Change Zoom hotkey (No Key Conflicts), the Standard x8 Scope changes zoom level as expected. Now switching my mainhand weapon to gun two, and the ELCAN scope's zoom level is changed into 4x Zoom Level due to the zoom change I did on gun one, which means zooming in on one scope would simultaneously trigger the zoom change function on other guns and thus causing other scopes on other guns to change their zoom level.

**Comment by ClumsyAlien** [comment]
Oh, that's not how it works however, if you swap your guns and hold a different zoom sight it will reset, the zoom state is global, this makes the handler simpler and less bug prone.
