### ISSUE TITLE
Optics not working when having shaders on

### ISSUE THREAD

**Issue by Fiskambulans** [ClumsyAlien/TimelessandClassics_Reforged#103]
![2023-05-27_18 48 **29](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/assets/134800130/6ed3312f-c34a-4899-9eab-e7863adaf85f)**

Some optics are not working when I am using shaders (SEUS Shaders). I tried turning off DR for scopes but it still doesn't work. Some optics I have tried that are not working are  ELCAN SpecterDR 1x-4x, ACOG 4x, Trijicon SRO and many more. Is there any solution to this? If you need more information, ask me.

**Comment by Type-32** [comment]
Hey dude check out this: https://github.com/ClumsyAlien/TimelessandClassics_Reforged/issues/100
Turning off the DR in TAC GUI should help.

**Comment by Fiskambulans** [comment]
Turning off DR fixes some scopes like for example the Standard 8x scope, but for other optics that are not scopes this doesn't help.

**Comment by ClumsyAlien** [comment]
Seus seems to not support transparency on a held item, either switch your shaders or remove shaders all together, only future versions of TaC remove glass on optics to bypass weird issues like this.
