### ISSUE TITLE
[suggestion] Removable bipods

### ISSUE THREAD

**Issue by JukoiDev** [ClumsyAlien/TimelessandClassics_Reforged#14]
I suggest making slot for bipods and other extras(maybe you can use that 4 slots on right side), so you can pull bipods out. They can be already in that slot for some weapons(like DP-28).

**Comment by ClumsyAlien** [comment]
Already planned, please join the Timeless Discord if you plan on sharing suggestions as Github is for major bug reports and inner update work. This thread will now be closed.
