### ISSUE TITLE
[suggestion] Nerfing supressor

### ISSUE THREAD

**Issue by JukoiDev** [ClumsyAlien/TimelessandClassics_Reforged#15]
I think supressors are overpowered. They have many pros but no cons. Supressor slows down bullet, so it means lower damage. I suggest damage lose about 1 or 1.5 hp.

**Comment by ClumsyAlien** [comment]
There has even already been a post about "nerfing of suppressors", this is not planned and I have already shared an explanation here ([https://github.com/ClumsyAlien/TimelessandClassics_Reforged/issues/13]), once again join our Discord if you wish for us to take your suggestions more seriously and for others to provide popper comments on your ideas. 

Along with this do not repost the same report over and over again on Github as I have also just noticed you were the person who created the earlier post about suppressors and I don't plan on rewriting every thing I wrote before to answer your inquiry.
