### ISSUE TITLE
随机空指针异常跳出

### ISSUE THREAD

**Issue by Ember213021** [ClumsyAlien/TimelessandClassics_Reforged#16]
游戏过程中随机跳出，查看Log发现跳出位置如下：
Random crash during gameplay,log shows a NullPointerException like this:

>  java.lang.NullPointerException: Unexpected error
> 	at com.tac.guns.client.handler.GunRenderingHandler.onRenderOverlay(GunRenderingHandler.java:264) ~[?:0.1.4.1-1.16.5] {re:classloading}

完整日志:

[crash-2021-12-11_01.18.03-client.txt](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/7694432/crash-2021-12-11_01.18.03-client.txt)

**Comment by ClumsyAlien** [comment]
Update to the latest public version of TaC on Curseforge.
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
