### ISSUE TITLE
Incompatible with Valkyrien Skies

### ISSUE THREAD

**Issue by supershorty1** [ClumsyAlien/TimelessandClassics_Reforged#160]
[default.txt](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/13402560/default.txt)
[latest.log](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/13402561/latest.log)
[debug.log](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/13402562/debug.log)
Minecraft 1.18.2 with forge 40.2.14

**Comment by supershorty1** [comment]
Fixed

**Comment by MRxTRASH** [comment]
i have the same issue right now how did you fix it?
