### ISSUE TITLE
Just Enough Items失效

### ISSUE THREAD

**Issue by Ember213021** [ClumsyAlien/TimelessandClassics_Reforged#17]
安装Reforged最新版本（timeless_and_classics-gun_mod-0.1.4.1-1.16.5.jar）后进入游戏，JEI功能完全失效；无任何错误提示或异常日志

Newest version （timeless_and_classics-gun_mod-0.1.4.1-1.16.5.jar） makes JEI fail to work,all JEI functions are not usable while this mod is loaded.No error log or anything like that

**Comment by ClumsyAlien** [comment]
Update to the latest public version of TaC on Curseforge.
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
