### ISSUE TITLE
Make the mod for 1.20.1 & Fabric Support

### ISSUE THREAD

**Issue by lu2000luk** [ClumsyAlien/TimelessandClassics_Reforged#177]
Many mods (Including stuff like create) are for 1.20.1 and, also, 1.16 (even if its cool) is a bit old and i personally make every modpack for 1.20.1 as i think is one (if not the best) new version for mods.

ALSO

Fabric as a modloader is way more modern than forge, its more optimized and has an huge dev. community that can help with the development

**Comment by Mercuriousity** [comment]
Wow, if only we have a magical line of code that can single-handedly porting to 1.20.1 and Fabric and be perfectly playable.

Jokes aside they are only humans, their ability capacity is limited, if you want this to be done so much, consider having a taste of what porting, maintaining and developing this mod taste like.

**Comment by lu2000luk** [comment]
Yeah, this was just a reccomandation, no pressure ofc
