### ISSUE TITLE
Guns Uncraftable on dedicated Server

### ISSUE THREAD

**Issue by yor42** [ClumsyAlien/TimelessandClassics_Reforged#18]
On multiplayer server Clicking craft button on workbench doesn't do anything.
It doesnt't take resource nor it gives player gun. no error log, but I do think its side issue of workbench
giving player gun on client side instead of server since it works on single player server.

**Comment by MichaelKono** [comment]
Well any normal log files? Mc and forge version? Currently workbenches work on my installs so I can't help you without more direct information.

**Comment by awbuckst11181999** [comment]
How did you solve this?

**Comment by yor42** [comment]
Its issue of only few guns. other guns worked fine on me.
