### ISSUE TITLE
Ammo type "Air"

### ISSUE THREAD

**Issue by ElgerElg** [ClumsyAlien/TimelessandClassics_Reforged#192]
Idk why... Maybe data lost or player cache lost. Also bug with aiming camera
![image](https://github.com/user-attachments/assets/c214a6b3-d935-49e1-943f-ca45a8dacda6)
![image](https://github.com/user-attachments/assets/43963848-cc7b-45ab-a143-f010568bac35)

**Comment by ElgerElg** [comment]
After updating TAC configs and reload server it's fixed but some players can't shoot

**Comment by ElgerElg** [comment]
Idk what to do

**Comment by ElgerElg** [comment]
Nice support

**Comment by ElgerElg** [comment]
![image](https://github.com/user-attachments/assets/7e6da1a3-0e0e-4402-a64b-b1b6bf2be7ce)

**Comment by gumelthemodeler** [comment]
Hey moron. This github is old and so is the mod version. Go to the TACZ discord or something.

**Comment by ElgerElg** [comment]
I already fixed this. 
Poor. No support for old mods... Like a Windows 7 💩
