### ISSUE TITLE
I need 1.12.2 

### ISSUE THREAD

**Issue by Dedeyeager** [ClumsyAlien/TimelessandClassics_Reforged#23]
I'm making a modpack but only for me and this mod just like gets together with the modpack and if you could please reply with yes or no

**Comment by Kacper531** [comment]
we will never downgrade to 1.12, it's literally the least stonks decision you could make for the mod

for the last time, no

**Comment by Dedeyeager** [comment]
No problem

Em sáb, 26 de mar de 2022 19:34, Kacper531 ***@***.***>
escreveu:

**Comment by Dedeyeager** [comment]
No problem I actually found a mod who is for 1.12.2 that has some good weapons and I have a bunch off gun mods now

**Comment by Kacper531** [comment]
ok, and?

**Comment by Dedeyeager** [comment]
It means i dont need It
