### ISSUE TITLE
[BUG] Glock-17 game crash when aiming in server

### ISSUE THREAD

**Issue by Malex21** [ClumsyAlien/TimelessandClassics_Reforged#24]
Title.
If I try to aim with a Glock-17 in a server, it immediatly crashes. (Like, instantly !)
Optifine does not seem to be the cause, too (happens with and without it)

https://bytebin.lucko.me/o6462qPES9
Crash log when aiming

Minecraft Java Edition
Forge 36.2.31
Minecraft 1.16.5

**Comment by ClumsyAlien** [comment]
Update to the latest public version of TaC on Curseforge.
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
