### ISSUE TITLE
1.16.5 TAC 0.2.0版本部分武器弹匣容量错误

### ISSUE THREAD

**Issue by Tarukice** [ClumsyAlien/TimelessandClassics_Reforged#31]
部分武器的弹匣容量出现问题，装填子弹是正常的（图中的31发只填到30发，即原本的弹夹容量），但可以二次填弹（填到31发）
![$NDID{)B0P1)_UKB`%X3)JX](https://user-images.githubusercontent.com/100508862/173177270-1bab7139-44ef-43dc-9fd6-6ac71e8d5954.png)

**Comment by Tarukice** [comment]
在线等，急

**Comment by ClumsyAlien** [comment]
This is not a problem, this is a closed bolt weapon, we run only a single mag reload when guns are created from a creative inventory, which means the bolt must be racked before fire, this is done for realism once we finish our animation system, and really has no effect to gameplay other then "Oh right, closed bolt, this actually has 31 max not 30".
