### ISSUE TITLE
[Crash] Random NullPointerException occurs when moving guns from a chest to player inventory

### ISSUE THREAD

**Issue by PeterBennyFooda** [ClumsyAlien/TimelessandClassics_Reforged#62]
Hi, I tried the latest 0.3.4 alpha and found this issue.

Sometimes when I moved a gun from a chest to the inventory, the game suddenly closed and the crash log said that it's caused by `com.tac.guns.client.handler.GunRenderingHandler.onFovModifying(GunRenderingHandler.java:199)`.

I thought it was other mods that conflict with gun rendering at first so I removed all mods that may render 3D models in game.
However, the problem still exists so I decided to open a issue here.

I've tried many times with different guns and the game still crashed. 

Full Log:  [crash-2023-02-02_01.24.48-client.txt](https://github.com/ClumsyAlien/TimelessandClassics_Reforged/files/10559977/crash-2023-02-02_01.24.48-client.txt)

Version: tac-a-0.3.4-1.16.5

**Comment by ClumsyAlien** [comment]
Looks valid, good catch, soon upcoming version 0.3.5 will contain a fix.

**Comment by ClumsyAlien** [comment]
Updating to the latest version should fix this,
https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac
