### ISSUE TITLE
Minor errors with the mod

### ISSUE THREAD

**Issue by ExodusBF4** [ClumsyAlien/TimelessandClassics_Reforged#7]
Since you (ClumsyAlien) have ignored my feedback in the discord server, i'm forced to make this github bug report. Telling me to "make a datapack" or "fix it yourself" because i noticed an issue with the mod is lazy on your end and very rude. Stop being so arrogant, it is not my responsibility to fix your mod, that is your job as the mod maker.
-Mossberg 590's name is incorrect, it is spelled "Mosberg 590", fix your typo
-AK74 model is incorrect, the gas block is the old AKM style 45-degree gas block instead of the proper 90-degree gas block the 74 uses, fix your model

**Comment by Kacper531** [comment]
amogus

**Comment by ExodusBF4** [comment]
stop acting so fucking smug

**Comment by ExodusBF4** [comment]
lol my responses to this get posted in the discord server

**Comment by ClumsyAlien** [comment]
This issue is now closed, Beta 0.1.0 addresses this thread.
