### ISSUE TITLE
Reload and equip sounds multiplayer bug

### ISSUE THREAD

**Issue by Sam55161** [ClumsyAlien/TimelessandClassics_Reforged#76]
When using any gun in multiplayer, other players can hear sounds of equipping or reloading at full volume from anywhere within their render distance. The bug was noticed when players were far away enough to not hear the gunshots from a shootout but could still hear all the reload sounds at an extremely loud volume.

**Comment by ClumsyAlien** [comment]
Install the dynamic sounds mod 
https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings
