### ISSUE TITLE
Unable to Use Attachments on Server

### ISSUE THREAD

**Issue by sqozilla** [ClumsyAlien/TimelessandClassics_Reforged#97]
Attachments don't persist on weapons. Console fills with the pasted error:

https://pastebin.com/RxL0vXcW

Also unable to change reassign controls and keybinds for the mod.

**Comment by ClumsyAlien** [comment]
I was unable to replicate your attachments issue, possibly already fixed from general improvements?

Anyway, the Keybinds issue is solved for 1.18+, a new alpha is already being prepped.

**Comment by ClumsyAlien** [comment]
Provide more detail after testing the next version 👍 (Post the whole game log where the error occurred, only an error log doesn't provide context such as modset used)
