### ISSUE TITLE
Gun Audio plays for all players on server at long distance

### ISSUE THREAD

**Issue by XSubbyteX** [ClumsyAlien/TimelessandClassics_Reforged#99]
I have added this mod to a java server I am hosting. One issue is that the reload and shot audio for weapons are played for everyone on the server even if they don't have a weapon. 

My GF play this mod with me but she hates how she is mining and when I reload my shotgun it plays loudly for her as if she has the weapon herself.

Can there be a feature we're players can manage these audio settings as well? The only way around it is to decrease the player volume but it seems to block out other needed audio as well.

**Comment by ClumsyAlien** [comment]
You can already adjust the audio setting of gun actions in the TaC menu, top left when inside of the video settings screen. Plus if your on 1.16 use Dynamic Sounds, it's impossible without implementing an entirely new sound engine to solve this problem without having server incompatible sounds.
